#!/usr/bin/env bash

# fzf and cd to directory in current dir
# also supports left/right arrow keys to go up/down
# one layer, and repeat in new folder
# Source: https://github.com/nguyenvukhang/dots/blob/master/zsh/.config/zsh/jump

function g() {
    # if directory has no children directory, end
    local check=$(command ls -Ap)
    [[ ! $check = *"/"* ]] && return 0

    # main searching command
    local target=$(fdfind --hidden -t d --exclude ".git" \
        | fzf --expect "enter,esc,left,right")

    target=${target#/*}

    local res=()
    while IFS= read -r line; do
        res+=( "$line" )
    done < <( echo "$target" )

    local key=${res[0]}
    local location=${res[1]}

    case $key in
        'esc') return 0 ;;
        'left') cd ../ && g ;;
        'right') cd "$location" && g ;;
        'enter') cd "$location" ;;
        *) return 0 ;;
    esac
    unset key location
}
