#!/usr/bin/env bash

declare -A nav=(
  [d]="$DOTS"
  [z]="$ZSH_DOTS"
  [r]="$REPOS"
  [t]="$DOTS/tmux/.config/tmux"
  [nv]="$NAVI_PATH"
  [n]="$DOTS/nvim/.config/nvim"
)

for k in "${!nav[@]}"; do
  dir="${nav[$k]}"
  [ ! -d "$dir" ] && echo "bash nav: $dir doesn't exist" && continue
  alias "2$k"="cd '$dir'"
done
unset nav k dir 
