#!/usr/bin/env zsh

typeset -A local nav=(
  [d]="$DOTS"
  [z]="$ZSH_DOTS"
  [r]="$REPOS"
  [t]="$DOTS/tmux/.config/tmux"
  [nv]="$NAVI_PATH"
  [n]="$DOTS/nvim/.config/nvim"
)

for k dir in ${(kv)nav}; do
  [ ! -d $dir ] && echo "zsh nav: $dir doesn't exist" && continue
  alias 2$k="cd $dir"
done
unset nav k v
